question_api_data = [
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Ashley Frangipane performs under the stage name Halsey.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Art", "type": "boolean", "difficulty": "medium",
     "question": "Pablo Picasso is one of the founding fathers of &quot;Cubism.&quot;",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "United States President Ronald Reagan was the first president to appoint a woman ",
     "to the Supreme Court. "
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "EDM label Monstercat signs tracks instead of artists.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
     "question": "E = MC3",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "3 members of 2 Live Crew were arrested for playing songs from their album, As Nasty "
     "As They Wanna Be, live.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean",
     "difficulty": "medium",
     "question": "Klingons once had a period of Democracy in their history, they referred to it as the "
     "&quot;Dark Times&quot;.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}
]